# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: psi.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'psi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpsi.proto\x12\tpsi_proto\"\xdb\x02\n\x0bServerSetup\x12-\n\x03raw\x18\x01 \x01(\x0b\x32\x1e.psi_proto.ServerSetup.RawInfoH\x00\x12-\n\x03gcs\x18\x02 \x01(\x0b\x32\x1e.psi_proto.ServerSetup.GCSInfoH\x00\x12>\n\x0c\x62loom_filter\x18\x03 \x01(\x0b\x32&.psi_proto.ServerSetup.BloomFilterInfoH\x00\x1a%\n\x07RawInfo\x12\x1a\n\x12\x65ncrypted_elements\x18\x01 \x03(\x0c\x1a\x38\n\x07GCSInfo\x12\x0b\n\x03\x64iv\x18\x01 \x01(\x05\x12\x12\n\nhash_range\x18\x02 \x01(\x03\x12\x0c\n\x04\x62its\x18\x03 \x01(\x0c\x1a;\n\x0f\x42loomFilterInfo\x12\x1a\n\x12num_hash_functions\x18\x01 \x01(\x05\x12\x0c\n\x04\x62its\x18\x02 \x01(\x0c\x42\x10\n\x0e\x64\x61ta_structure\"B\n\x07Request\x12\x1b\n\x13reveal_intersection\x18\x01 \x01(\x08\x12\x1a\n\x12\x65ncrypted_elements\x18\x02 \x03(\x0c\"&\n\x08Response\x12\x1a\n\x12\x65ncrypted_elements\x18\x01 \x03(\x0c\x42\x1dZ\x1bgithub.com/openmined/psi/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'psi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033github.com/openmined/psi/pb'
  _globals['_SERVERSETUP']._serialized_start=25
  _globals['_SERVERSETUP']._serialized_end=372
  _globals['_SERVERSETUP_RAWINFO']._serialized_start=198
  _globals['_SERVERSETUP_RAWINFO']._serialized_end=235
  _globals['_SERVERSETUP_GCSINFO']._serialized_start=237
  _globals['_SERVERSETUP_GCSINFO']._serialized_end=293
  _globals['_SERVERSETUP_BLOOMFILTERINFO']._serialized_start=295
  _globals['_SERVERSETUP_BLOOMFILTERINFO']._serialized_end=354
  _globals['_REQUEST']._serialized_start=374
  _globals['_REQUEST']._serialized_end=440
  _globals['_RESPONSE']._serialized_start=442
  _globals['_RESPONSE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
