# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: restaurant.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
import sys 
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'restaurant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import p2p.psi_pb2 as psi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10restaurant.proto\x12\tpsi_proto\x1a\tpsi.proto\"%\n\x0cSetupRequest\x12\x15\n\rnum_customers\x18\x01 \x01(\r\"J\n\nSetupReply\x12%\n\x05setup\x18\x01 \x01(\x0b\x32\x16.psi_proto.ServerSetup\x12\x15\n\rrestaurantKey\x18\x02 \x01(\t\"6\n\x0f\x43ustomerRequest\x12#\n\x07request\x18\x01 \x01(\x0b\x32\x12.psi_proto.Request\"6\n\rCustomerReply\x12%\n\x08response\x18\x01 \x01(\x0b\x32\x13.psi_proto.Response2\x90\x01\n\x12RestaurantNeighbor\x12\x39\n\x05Setup\x12\x17.psi_proto.SetupRequest\x1a\x15.psi_proto.SetupReply\"\x00\x12?\n\x05\x46\x65tch\x12\x1a.psi_proto.CustomerRequest\x1a\x18.psi_proto.CustomerReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'restaurant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETUPREQUEST']._serialized_start=42
  _globals['_SETUPREQUEST']._serialized_end=79
  _globals['_SETUPREPLY']._serialized_start=81
  _globals['_SETUPREPLY']._serialized_end=155
  _globals['_CUSTOMERREQUEST']._serialized_start=157
  _globals['_CUSTOMERREQUEST']._serialized_end=211
  _globals['_CUSTOMERREPLY']._serialized_start=213
  _globals['_CUSTOMERREPLY']._serialized_end=267
  _globals['_RESTAURANTNEIGHBOR']._serialized_start=270
  _globals['_RESTAURANTNEIGHBOR']._serialized_end=414
# @@protoc_insertion_point(module_scope)
