# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x0fwaku.message.v1\"\xf3\x01\n\x0bWakuMessage\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x15\n\rcontent_topic\x18\x02 \x01(\t\x12\x14\n\x07version\x18\x03 \x01(\rH\x00\x88\x01\x01\x12\x16\n\ttimestamp\x18\n \x01(\x12H\x01\x88\x01\x01\x12\x11\n\x04meta\x18\x0b \x01(\x0cH\x02\x88\x01\x01\x12\x16\n\tephemeral\x18\x1f \x01(\x08H\x03\x88\x01\x01\x12\x1d\n\x10rate_limit_proof\x18\x15 \x01(\x0cH\x04\x88\x01\x01\x42\n\n\x08_versionB\x0c\n\n_timestampB\x07\n\x05_metaB\x0c\n\n_ephemeralB\x13\n\x11_rate_limit_proofb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WAKUMESSAGE']._serialized_start=35
  _globals['_WAKUMESSAGE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
