// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: order.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Proof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buf           []byte                 `protobuf:"bytes,1,opt,name=buf,proto3" json:"buf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proof) Reset() {
	*x = Proof{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proof) ProtoMessage() {}

func (x *Proof) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proof.ProtoReflect.Descriptor instead.
func (*Proof) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Proof) GetBuf() []byte {
	if x != nil {
		return x.Buf
	}
	return nil
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Now           string                 `protobuf:"bytes,1,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *Timestamp) GetNow() string {
	if x != nil {
		return x.Now
	}
	return ""
}

type SignedPreKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedPreKey  []byte                 `protobuf:"bytes,1,opt,name=signed_pre_key,json=signedPreKey,proto3" json:"signed_pre_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPreKey) Reset() {
	*x = SignedPreKey{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPreKey) ProtoMessage() {}

func (x *SignedPreKey) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPreKey.ProtoReflect.Descriptor instead.
func (*SignedPreKey) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *SignedPreKey) GetSignedPreKey() []byte {
	if x != nil {
		return x.SignedPreKey
	}
	return nil
}

type Bundle struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Identity      []byte                   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	SignedPreKeys map[string]*SignedPreKey `protobuf:"bytes,2,rep,name=signed_pre_keys,json=signedPreKeys,proto3" json:"signed_pre_keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Signature     []byte                   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp     int64                    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *Bundle) GetIdentity() []byte {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Bundle) GetSignedPreKeys() map[string]*SignedPreKey {
	if x != nil {
		return x.SignedPreKeys
	}
	return nil
}

func (x *Bundle) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Bundle) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ENR           string                 `protobuf:"bytes,2,opt,name=ENR,proto3" json:"ENR,omitempty"`
	Bundle        *Bundle                `protobuf:"bytes,3,opt,name=Bundle,proto3" json:"Bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *Identity) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Identity) GetENR() string {
	if x != nil {
		return x.ENR
	}
	return ""
}

func (x *Identity) GetBundle() *Bundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

type Approval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []string               `protobuf:"bytes,1,rep,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Approval) Reset() {
	*x = Approval{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Approval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Approval) ProtoMessage() {}

func (x *Approval) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Approval.ProtoReflect.Descriptor instead.
func (*Approval) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *Approval) GetSignature() []string {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Peers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	SubDomain     []string               `protobuf:"bytes,2,rep,name=subDomain,proto3" json:"subDomain,omitempty"`
	Approval      *Approval              `protobuf:"bytes,3,opt,name=approval,proto3,oneof" json:"approval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peers) Reset() {
	*x = Peers{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peers) ProtoMessage() {}

func (x *Peers) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peers.ProtoReflect.Descriptor instead.
func (*Peers) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *Peers) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Peers) GetSubDomain() []string {
	if x != nil {
		return x.SubDomain
	}
	return nil
}

func (x *Peers) GetApproval() *Approval {
	if x != nil {
		return x.Approval
	}
	return nil
}

type Inference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inference) Reset() {
	*x = Inference{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inference) ProtoMessage() {}

func (x *Inference) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inference.ProtoReflect.Descriptor instead.
func (*Inference) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *Inference) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         *Proof                 `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	Timestamp     *Timestamp             `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Identity      *Identity              `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	Inference     *Inference             `protobuf:"bytes,4,opt,name=inference,proto3" json:"inference,omitempty"`
	Peers         *Peers                 `protobuf:"bytes,5,opt,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *OrderRequest) GetProof() *Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *OrderRequest) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *OrderRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *OrderRequest) GetInference() *Inference {
	if x != nil {
		return x.Inference
	}
	return nil
}

func (x *OrderRequest) GetPeers() *Peers {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x04main\"\x19\n" +
	"\x05Proof\x12\x10\n" +
	"\x03buf\x18\x01 \x01(\fR\x03buf\"\x1d\n" +
	"\tTimestamp\x12\x10\n" +
	"\x03now\x18\x01 \x01(\tR\x03now\"4\n" +
	"\fSignedPreKey\x12$\n" +
	"\x0esigned_pre_key\x18\x01 \x01(\fR\fsignedPreKey\"\xff\x01\n" +
	"\x06Bundle\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\fR\bidentity\x12G\n" +
	"\x0fsigned_pre_keys\x18\x02 \x03(\v2\x1f.main.Bundle.SignedPreKeysEntryR\rsignedPreKeys\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x1aT\n" +
	"\x12SignedPreKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.main.SignedPreKeyR\x05value:\x028\x01\"R\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x10\n" +
	"\x03ENR\x18\x02 \x01(\tR\x03ENR\x12$\n" +
	"\x06Bundle\x18\x03 \x01(\v2\f.main.BundleR\x06Bundle\"(\n" +
	"\bApproval\x12\x1c\n" +
	"\tsignature\x18\x01 \x03(\tR\tsignature\"u\n" +
	"\x05Peers\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1c\n" +
	"\tsubDomain\x18\x02 \x03(\tR\tsubDomain\x12/\n" +
	"\bapproval\x18\x03 \x01(\v2\x0e.main.ApprovalH\x00R\bapproval\x88\x01\x01B\v\n" +
	"\t_approval\"\x1f\n" +
	"\tInference\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\"\xde\x01\n" +
	"\fOrderRequest\x12!\n" +
	"\x05proof\x18\x01 \x01(\v2\v.main.ProofR\x05proof\x12-\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x0f.main.TimestampR\ttimestamp\x12*\n" +
	"\bidentity\x18\x03 \x01(\v2\x0e.main.IdentityR\bidentity\x12-\n" +
	"\tinference\x18\x04 \x01(\v2\x0f.main.InferenceR\tinference\x12!\n" +
	"\x05peers\x18\x05 \x01(\v2\v.main.PeersR\x05peersB\tZ\a./;mainb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_order_proto_goTypes = []any{
	(*Proof)(nil),        // 0: main.Proof
	(*Timestamp)(nil),    // 1: main.Timestamp
	(*SignedPreKey)(nil), // 2: main.SignedPreKey
	(*Bundle)(nil),       // 3: main.Bundle
	(*Identity)(nil),     // 4: main.Identity
	(*Approval)(nil),     // 5: main.Approval
	(*Peers)(nil),        // 6: main.Peers
	(*Inference)(nil),    // 7: main.Inference
	(*OrderRequest)(nil), // 8: main.OrderRequest
	nil,                  // 9: main.Bundle.SignedPreKeysEntry
}
var file_order_proto_depIdxs = []int32{
	9, // 0: main.Bundle.signed_pre_keys:type_name -> main.Bundle.SignedPreKeysEntry
	3, // 1: main.Identity.Bundle:type_name -> main.Bundle
	5, // 2: main.Peers.approval:type_name -> main.Approval
	0, // 3: main.OrderRequest.proof:type_name -> main.Proof
	1, // 4: main.OrderRequest.timestamp:type_name -> main.Timestamp
	4, // 5: main.OrderRequest.identity:type_name -> main.Identity
	7, // 6: main.OrderRequest.inference:type_name -> main.Inference
	6, // 7: main.OrderRequest.peers:type_name -> main.Peers
	2, // 8: main.Bundle.SignedPreKeysEntry.value:type_name -> main.SignedPreKey
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	file_order_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
