// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: sync.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DummyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyRequest) Reset() {
	*x = DummyRequest{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyRequest) ProtoMessage() {}

func (x *DummyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyRequest.ProtoReflect.Descriptor instead.
func (*DummyRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *DummyRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*SyncRequest_Order
	//	*SyncRequest_Dummy
	Type          isSyncRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncRequest) GetType() isSyncRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *SyncRequest) GetOrder() *OrderRequest {
	if x != nil {
		if x, ok := x.Type.(*SyncRequest_Order); ok {
			return x.Order
		}
	}
	return nil
}

func (x *SyncRequest) GetDummy() *DummyRequest {
	if x != nil {
		if x, ok := x.Type.(*SyncRequest_Dummy); ok {
			return x.Dummy
		}
	}
	return nil
}

type isSyncRequest_Type interface {
	isSyncRequest_Type()
}

type SyncRequest_Order struct {
	Order *OrderRequest `protobuf:"bytes,1,opt,name=order,proto3,oneof"`
}

type SyncRequest_Dummy struct {
	Dummy *DummyRequest `protobuf:"bytes,2,opt,name=dummy,proto3,oneof"`
}

func (*SyncRequest_Order) isSyncRequest_Type() {}

func (*SyncRequest_Dummy) isSyncRequest_Type() {}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\x04main\x1a\vorder.proto\"$\n" +
	"\fDummyRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"m\n" +
	"\vSyncRequest\x12*\n" +
	"\x05order\x18\x01 \x01(\v2\x12.main.OrderRequestH\x00R\x05order\x12*\n" +
	"\x05dummy\x18\x02 \x01(\v2\x12.main.DummyRequestH\x00R\x05dummyB\x06\n" +
	"\x04typeB\tZ\a./;mainb\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sync_proto_goTypes = []any{
	(*DummyRequest)(nil), // 0: main.DummyRequest
	(*SyncRequest)(nil),  // 1: main.SyncRequest
	(*OrderRequest)(nil), // 2: main.OrderRequest
}
var file_sync_proto_depIdxs = []int32{
	2, // 0: main.SyncRequest.order:type_name -> main.OrderRequest
	0, // 1: main.SyncRequest.dummy:type_name -> main.DummyRequest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	file_order_proto_init()
	file_sync_proto_msgTypes[1].OneofWrappers = []any{
		(*SyncRequest_Order)(nil),
		(*SyncRequest_Dummy)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
